# Generated by Django 4.1 on 2022-09-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mozo',
            name='sector',
            field=models.CharField(max_length=50),
        ),
    ]
