# Generated by Django 4.1 on 2022-09-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_producto_rename_order_pedido_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resto.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resto.producto'),
        ),
    ]
