# Generated by Django 4.1 on 2022-09-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_pedido_cliente_pedido_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('Apto Vegano', 'Apto Vegano'), ('No apto Vegano', 'No apto Vegano')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(to='resto.tag'),
        ),
    ]
