# Generated by Django 4.1 on 2022-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_tag_alter_producto_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], max_length=200, null=True),
        ),
    ]
